server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: amy
    password: 123456
    virtualHost: amy_host
    listener:
      simple:
        acknowledge-mode: auto  # 自动确认消息
      direct:
        acknowledge-mode: auto
        prefetch: 1
  devtools:
    livereload:
      port: 35732