spring:
  rabbitmq:
    host: 10.222.29.171
    port: 5672
    username: admin
    password: admin
    virtualHost: my_vhost
#    listener:
#      direct:
#        prefetch: 1
#        retry:
#          enabled: true
#          max-attempts: 5
#          max-interval: 100
